name: deploy web

on:
  push:
    branches: [prod]
  pull_request:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "20.17.0"

      - name: Clear cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Build Website
        run: npm run build
